import {
  galleryImg1,
  galleryImg2,
  galleryImg3,
  //galleryImg4,
  galleryImg5,
  serviceImg5,
  serviceImg6,
  serviceImg7,
  serviceImg8,
  serviceImg10,
  serviceImg11,
  serviceImg12,
  serviceImg13,
  serviceImg14,
  serviceImg15,
  serviceImg16,
  serviceImg17,
  serviceImg18,
  serviceimg9,
  serviceImg19,
  serviceImg20,
  serviceImg34,
  serviceImg35,
  serviceImg36,
  serviceImg37,
  serviceImg38,
  serviceImg39,
  serviceImg40,
  serviceImg41,
  
} from "../../public/assets/index";

const galleryData = [
  { id: 1, src: galleryImg1, alt: "galleryImg1" },
  { id: 2, src: galleryImg2, alt: "galleryImg2" },
  //{ id: 3, src: galleryImg3, alt: "galleryImg3" },
  //{ id: 4, src: galleryImg4, alt: "galleryImg4" },
  { id: 5, src: galleryImg5, alt: "galleryImg5" },
  { id: 6, src: galleryImg3, alt: "galleryImg3" },
  { id: 7, src: galleryImg3, alt: "galleryImg3" },
  { id: 8, src: serviceImg5, alt: "serviceImg5" },
  { id: 9, src: serviceImg6, alt: "serviceImg6" },
  { id: 10, src: serviceImg7, alt: "serviceImg7" },
  { id: 11, src: serviceImg8, alt: "serviceImg8" },
  { id: 12, src: serviceimg9, alt: "serviceImg9" },
  { id: 13, src: serviceImg10, alt: "serviceImg10" },
  { id: 14, src: serviceImg11, alt: "serviceImg11" },
  { id: 15, src: serviceImg12, alt: "serviceImg12" },
  //{ id: 16, src: serviceImg13, alt: "serviceImg13" },
  { id: 17, src: serviceImg14, alt: "serviceImg14" },
  { id: 18, src: serviceImg18, alt: "serviceImg18" },
  { id: 19, src: serviceImg19, alt: "serviceImg19" },
  { id: 20, src: serviceImg20, alt: "serviceImg20" },
  { id: 21, src: serviceImg34, alt: "serviceImg34" },
  { id: 22, src: serviceImg35, alt: "serviceImg35" },
  { id: 23, src: serviceImg36, alt: "serviceIm36" },
  { id: 24, src: serviceImg37, alt: "serviceImg37" },
  { id: 25, src: serviceImg38, alt: "serviceImg38" },
  { id: 26, src: serviceImg39, alt: "serviceImg39" },
  { id: 27, src: serviceImg40, alt: "serviceImg40" },
  { id: 28, src: serviceImg41, alt: "serviceImg41" },
];

export default galleryData;
